export interface USER_MODEL {
  id:number, 
  name:string, 
  email:string, 
  mobileNumber:string, 
  pincode:string, 
  address:string, 
  password:string
}

export const REGISTERED_USERS : USER_MODEL[] = [
    
  { id: 1, name: "John Doe", email: "john@example.com", mobileNumber: "1234567890", pincode: "12345", address: "123 Main St", password: "Karthic@1234" },
  { id: 2, name: "Jane Smith", email: "jane@example.com", mobileNumber: "9876543210", pincode: "54321", address: "456 Oak Ave", password: "strongPassword456" },
  { id: 3, name: "Alice Johnson", email: "alice@example.com", mobileNumber: "5551234567", pincode: "67890", address: "789 Elm Rd", password: "pass1234" },
  { id: 4, name: "Bob Williams", email: "bob@example.com", mobileNumber: "9998765432", pincode: "56789", address: "890 Birch Ln", password: "password987" },
  { id: 5, name: "Eva Davis", email: "eva@example.com", mobileNumber: "1112223333", pincode: "34567", address: "234 Pine St", password: "evaPass4321" },
  { id: 6, name: "Michael Brown", email: "michael@example.com", mobileNumber: "7778889999", pincode: "45678", address: "345 Cedar Dr", password: "brownPass6789" },
  { id: 7, name: "Olivia Miller", email: "olivia@example.com", mobileNumber: "3334445555", pincode: "98765", address: "456 Maple Ct", password: "olivia123" },
  { id: 8, name: "William Wilson", email: "william@example.com", mobileNumber: "2223334444", pincode: "23456", address: "567 Oak Ave", password: "wilsonPass" },
  { id: 9, name: "Sophia Taylor", email: "sophia@example.com", mobileNumber: "8889990000", pincode: "87654", address: "678 Pine St", password: "taylor987" },
  { id: 10, name: "James Lee", email: "james@example.com", mobileNumber: "6667778888", pincode: "34567", address: "789 Birch Ln", password: "leePass123" },
  { id: 11, name: "Ava White", email: "ava@example.com", mobileNumber: "4445556666", pincode: "23456", address: "890 Elm Rd", password: "avaPass" },
  { id: 12, name: "Liam Hall", email: "liam@example.com", mobileNumber: "5556667777", pincode: "45678", address: "123 Maple Ct", password: "hallPass" },
  { id: 13, name: "Emma Allen", email: "emma@example.com", mobileNumber: "1112223333", pincode: "98765", address: "234 Cedar Dr", password: "emma123" },
  { id: 14, name: "Noah Turner", email: "noah@example.com", mobileNumber: "9998887777", pincode: "87654", address: "345 Oak Ave", password: "noahPass" },
  { id: 15, name: "Isabella Brown", email: "isabella@example.com", mobileNumber: "8887776666", pincode: "23456", address: "456 Pine St", password: "isabella987" },
  { id: 16, name: "Jackson Davis", email: "jackson@example.com", mobileNumber: "4445556666", pincode: "34567", address: "567 Birch Ln", password: "jacksonPass" },
  { id: 17, name: "Aria Wilson", email: "aria@example.com", mobileNumber: "1112223333", pincode: "87654", address: "678 Maple Ct", password: "aria123" },
  { id: 18, name: "Lucas Smith", email: "lucas@example.com", mobileNumber: "6667778888", pincode: "23456", address: "789 Cedar Dr", password: "lucasPass" },
  { id: 19, name: "Grace Harris", email: "grace@example.com", mobileNumber: "5554443333", pincode: "45678", address: "890 Pine St", password: "grace987" },
  { id: 20, name: "Henry Johnson", email: "henry@example.com", mobileNumber: "2223334444", pincode: "34567", address: "123 Birch Ln", password: "henryPass" }

  ];
  
export const STATE_LIST = [
  { id: 1, state: "Andhra Pradesh" },
  { id: 2, state: "Arunachal Pradesh" },
  { id: 3, state: "Assam" },
  { id: 4, state: "Bihar" },
  { id: 5, state: "Chhattisgarh" },
  { id: 6, state: "Goa" },
  { id: 7, state: "Gujarat" },
  { id: 8, state: "Haryana" },
  { id: 9, state: "Himachal Pradesh" },
  { id: 10, state: "Jharkhand" },
  { id: 11, state: "Karnataka" },
  { id: 12, state: "Kerala" },
  { id: 13, state: "Madhya Pradesh" },
  { id: 14, state: "Maharashtra" },
  { id: 15, state: "Manipur" },
  { id: 16, state: "Meghalaya" },
  { id: 17, state: "Mizoram" },
  { id: 18, state: "Nagaland" },
  { id: 19, state: "Odisha" },
  { id: 20, state: "Punjab" },
  { id: 21, state: "Rajasthan" },
  { id: 22, state: "Sikkim" },
  { id: 23, state: "Tamil Nadu" },
  { id: 24, state: "Telangana" },
  { id: 25, state: "Tripura" },
  { id: 26, state: "Uttar Pradesh" },
  { id: 27, state: "Uttarakhand" },
  { id: 28, state: "West Bengal" }
]

export const DISTRICT_LIST = [
  { id: 1, district: "Ariyalur" },
  { id: 2, district: "Chengalpattu" },
  { id: 3, district: "Chennai" },
  { id: 4, district: "Coimbatore" },
  { id: 5, district: "Cuddalore" },
  { id: 6, district: "Dharmapuri" },
  { id: 7, district: "Dindigul" },
  { id: 8, district: "Erode" },
  { id: 9, district: "Kallakurichi" },
  { id: 10, district: "Kanchipuram" },
  { id: 11, district: "Kanyakumari" },
  { id: 12, district: "Karur" },
  { id: 13, district: "Krishnagiri" },
  { id: 14, district: "Madurai" },
  { id: 15, district: "Mayiladuthurai" },
  { id: 16, district: "Nagapattinam" },
  { id: 17, district: "Namakkal" },
  { id: 18, district: "Nilgiris" },
  { id: 19, district: "Perambalur" },
  { id: 20, district: "Pudukkottai" },
  { id: 21, district: "Ramanathapuram" },
  { id: 22, district: "Ranipet" },
  { id: 23, district: "Salem" },
  { id: 24, district: "Sivaganga" },
  { id: 25, district: "Tenkasi" },
  { id: 26, district: "Thanjavur" },
  { id: 27, district: "Theni" },
  { id: 28, district: "Thoothukudi" },
  { id: 29, district: "Tiruchirappalli" },
  { id: 30, district: "Tirunelveli" },
  { id: 31, district: "Tirupathur" },
  { id: 32, district: "Tiruppur" },
  { id: 33, district: "Tiruvallur" },
  { id: 34, district: "Tiruvannamalai" },
  { id: 35, district: "Tiruvarur" },
  { id: 36, district: "Vellore" },
  { id: 37, district: "Viluppuram" },
  { id: 38, district: "Virudhunagar" }
]

export const CITY_LIST = [
  { id: 1, city: "Coimbatore City", district: "Coimbatore" },
  { id: 2, city: "Tiruppur", district: "Coimbatore" },
  { id: 3, city: "Erode", district: "Erode" },
  { id: 4, city: "Perundurai", district: "Erode" },
  { id: 5, city: "Gobichettipalayam", district: "Erode" },
  { id: 6, city: "Salem", district: "Coimbatore" },
  { id: 7, city: "Pollachi", district: "Coimbatore" },
  { id: 8, city: "Bhavani", district: "Erode" },
  { id: 9, city: "Mettupalayam", district: "Coimbatore" },
  { id: 10, city: "Sathyamangalam", district: "Erode" },
  { id: 11, city: "Avanashi", district: "Coimbatore" },
  { id: 12, city: "Udumalpet", district: "Coimbatore" },
  { id: 13, city: "Palani", district: "Dindigul" },
  { id: 14, city: "Kangeyam", district: "Tiruppur" },
  { id: 15, city: "Bhavani Sagar", district: "Erode" },
  { id: 16, city: "Modakkurichi", district: "Erode" },
  { id: 17, city: "Kodumudi", district: "Erode" },
  { id: 18, city: "Gudalur", district: "The Nilgiris" },
  { id: 19, city: "Sathyamangalam", district: "Erode" },
  { id: 20, city: "Tiruchengode", district: "Namakkal" },
  { id: 21, city: "Mettur", district: "Erode" },
  { id: 22, city: "Avinashi", district: "Coimbatore" },
  { id: 23, city: "Sulur", district: "Coimbatore" },
  { id: 24, city: "Karamadai", district: "Coimbatore" },
  { id: 25, city: "Sathyamangalam", district: "Erode" },
  { id: 26, city: "Periyanaickenpalayam", district: "Coimbatore" },
  { id: 27, city: "Chennimalai", district: "Erode" },
  { id: 28, city: "Palladam", district: "Tiruppur" },
  { id: 29, city: "Kodumudi", district: "Erode" },
  { id: 30, city: "Gobichettipalayam", district: "Erode" }
]

export const HOBBY_LIST = [
  {id: 1, hobby: "Reading"},
  {id: 2, hobby: "Traveling"},
  {id: 3, hobby: "Sports"},
  {id: 4, hobby: "Music"},
  {id: 5, hobby: "Gardening"},
  {id: 6, hobby: "Cooking"},
  {id: 7, hobby: "Photography"},
  {id: 8, hobby: "Painting"},
  {id: 9, hobby: "Writing"},
  {id: 10, hobby: "Cycling"}
]
